//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuzzyLibUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuzzyShape
    {
        public FuzzyShape()
        {
            this.FuzzyTerms = new HashSet<FuzzyTerm>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string DataType { get; set; }
    
        public virtual ICollection<FuzzyTerm> FuzzyTerms { get; set; }
    }
}
