//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuzzyLibUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuzzyRule
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int ModuleId { get; set; }
    
        public virtual FuzzyModule FuzzyModule { get; set; }
    }
}
