//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuzzyLibUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuzzyModule
    {
        public FuzzyModule()
        {
            this.FuzzyRules = new HashSet<FuzzyRule>();
            this.FuzzyVariables = new HashSet<FuzzyVariable>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string DataType { get; set; }
    
        public virtual ICollection<FuzzyRule> FuzzyRules { get; set; }
        public virtual ICollection<FuzzyVariable> FuzzyVariables { get; set; }
    }
}
