//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuzzyLibUI
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuzzyTerm
    {
        public FuzzyTerm()
        {
            this.FuzzyTermParameters = new HashSet<FuzzyTermParameter>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ShapeId { get; set; }
        public int VariableId { get; set; }
    
        public virtual FuzzyShape FuzzyShape { get; set; }
        public virtual FuzzyVariable FuzzyVariable { get; set; }
        public virtual ICollection<FuzzyTermParameter> FuzzyTermParameters { get; set; }
    }
}
